sudo: required
services:
  - docker

before_install:
  - docker build -t web -f Dockerfile.dev .

script:
  - docker run web npm run test -- --coverage

deploy:
  provider: elasticbeanstack
  region: "us-east-1"
  app: "docker"
  env: 	"Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-966653973445"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"